name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/upload/images/ellipse-2.png
    - assets/upload/images/auto-group-bg2z.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-3-bg.png
    - assets/upload/images/ellipse-2-cem.png
    - assets/upload/images/ellipse-2-fMT.png
    - assets/upload/images/icon-bell.png
    - assets/upload/images/auto-group-gqpr.png
    - assets/upload/images/ellipse-3.png
    - assets/upload/images/auto-group-j8sp.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-2-bg.png
    - assets/upload/images/ellipse-2-DZK.png
    - assets/upload/images/icon-ticket-discount.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-1.png
    - assets/upload/images/ellipse-2-b4M.png
    - assets/upload/images/ellipse-3-uyT.png
    - assets/upload/images/screen-shot-2023-06-29-at-1443-1.png
    - assets/upload/images/ellipse-2-rMo.png
    - assets/upload/images/auto-group-uevb.png
    - assets/upload/images/ellipse-2-F8M.png
    - assets/upload/images/icon-bell-sBF.png
    - assets/upload/images/icon-message-edit.png
    - assets/upload/images/icon-bell-QmP.png
    - assets/upload/images/icon-minus-square.png
    - assets/upload/images/screen-shot-2023-06-29-at-1617-1.png
    - assets/upload/images/ellipse-3-b4d.png
    - assets/upload/images/auto-group-hiwp.png
    - assets/upload/images/icon-scan-barcode.png
    - assets/upload/images/icon-message-edit-At9.png
    - assets/upload/images/icon-home-2.png
    - assets/upload/images/footer.png
    - assets/upload/images/screen-shot-2023-06-29-at-1443-1-3mT.png
    - assets/upload/images/icon-logout.png
    - assets/upload/images/screen-shot-2023-06-28-at-1729-1.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-2-bg-nH7.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-1-SiD.png
    - assets/upload/images/icon-minus-square-wJq.png
    - assets/upload/images/icon-ticket-discount-b8V.png
    - assets/upload/images/auto-group-x8u5.png
    - assets/upload/images/icon-user.png
    - assets/upload/images/icon-scan-barcode-vXB.png
    - assets/upload/images/icon-scan-barcode-BNy.png
    - assets/upload/images/icon-message-edit-KEH.png
    - assets/upload/images/icon-minus-square-9UD.png
    - assets/upload/images/icon-user-yy3.png
    - assets/upload/images/footer-ZCV.png
    - assets/upload/images/icon-user-aBb.png
    - assets/upload/images/icon-home-2-FXo.png
    - assets/upload/images/icon-ticket-discount-V3o.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-3.png
    - assets/upload/images/icon-minus-square-f2h.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-1-vUR.png
    - assets/upload/images/frame-21.png
    - assets/upload/images/icon-minus-square-pZf.png
    - assets/upload/images/icon-ticket-discount-E4y.png
    - assets/upload/images/icon-ticket-discount-Ldo.png
    - assets/upload/images/icon-message-edit-M6y.png
    - assets/upload/images/frame-21-52y.png
    - assets/upload/images/icon-bell-bX7.png
    - assets/upload/images/icon-minus-square-H6R.png
    - assets/upload/images/ellipse-3-Tn9.png
    - assets/upload/images/ellipse-3-HRb.png
    - assets/upload/images/icon-message-edit-Qm7.png
    - assets/upload/images/icon-minus-square-pcH.png
    - assets/upload/images/icon-home-2-pBb.png
    - assets/upload/images/icon-bell-ugD.png
    - assets/upload/images/icon-home-2-EiV.png
    - assets/upload/images/icon-bell-dsf.png
    - assets/upload/images/icon-user-jvh.png
    - assets/upload/images/icon-bell-bxD.png
    - assets/upload/images/footer-kKK.png
    - assets/upload/images/footer-SWu.png
    - assets/upload/images/icon-user-7VB.png
    - assets/upload/images/icon-minus-square-Nvm.png
    - assets/upload/images/icon-minus-square-QPb.png
    - assets/upload/images/icon-minus-square-YVo.png
    - assets/upload/images/icon-minus-square-uUm.png
    - assets/upload/images/icon-ticket-discount-F2q.png
    - assets/upload/images/icon-minus-square-gtq.png
    - assets/upload/images/icon-magnifying-glass.png
    - assets/upload/images/ellipse-2-ETj.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-1-wVB.png
    - assets/upload/images/footer-RCd.png
    - assets/upload/images/screen-shot-2023-06-28-at-1729-1-cND.png
    - assets/upload/images/frame-21-zhP.png
    - assets/upload/images/icon-trip-map.png
    - assets/upload/images/icon-minus-square-dDb.png
    - assets/upload/images/icon-home-2-Jbs.png
    - assets/upload/images/auto-group-bhe5.png
    - assets/upload/images/icon-home-2-11s.png
    - assets/upload/images/icon-scan-barcode-EbK.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-2.png
    - assets/upload/images/icon-bell-Soj.png
    - assets/upload/images/icon-ticket-discount-xn5.png
    - assets/upload/images/icon-user-DkV.png
    - assets/upload/images/frame-21-mLd.png
    - assets/upload/images/icon-message-edit-9LM.png
    - assets/upload/images/ellipse-2-gr5.png
    - assets/upload/images/footer-Ag1.png
    - assets/upload/images/footer-WUH.png
    - assets/upload/images/icon-bell-RMb.png
    - assets/upload/images/icon-minus-square-tQ1.png
    - assets/upload/images/icon-scan-barcode-h5B.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-2-VMj.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-2-bg-Jzd.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-1-G3b.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-2-4HX.png
    - assets/upload/images/icon-scan-barcode-Ri1.png
    - assets/upload/images/frame-21-h7X.png
    - assets/upload/images/icon-minus-square-KgD.png
    - assets/upload/images/icon-message-edit-Raq.png
    - assets/upload/images/icon-home-2-b2y.png
    - assets/upload/images/icon-minus-square-heR.png
    - assets/upload/images/icon-user-MuK.png
    - assets/upload/images/icon-home-2-eJ5.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-1-PPX.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-2-h7w.png
    - assets/upload/images/footer-7HT.png
    - assets/upload/images/icon-user-J4y.png
    - assets/upload/images/icon-minus-square-qAZ.png
    - assets/upload/images/icon-minus-square-Neu.png
    - assets/upload/images/icon-ticket-discount-y5T.png
    - assets/upload/images/icon-bell-dpm.png
    - assets/upload/images/icon-message-edit-QU1.png
    - assets/upload/images/icon-minus-square-MTX.png
    - assets/upload/images/icon-ticket-discount-gMF.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-1-GGR.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-1-sWq.png
    - assets/upload/images/icon-minus-square-WMo.png
    - assets/upload/images/icon-minus-square-2Pj.png
    - assets/upload/images/icon-minus-square-USM.png
    - assets/upload/images/icon-home-2-SZX.png
    - assets/upload/images/icon-minus-square-J9P.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-2-9r1.png
    - assets/upload/images/icon-user-pcR.png
    - assets/upload/images/icon-bell-GFb.png
    - assets/upload/images/icon-minus-square-UGR.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-1-jqs.png
    - assets/upload/images/ellipse-3-7jX.png
    - assets/upload/images/icon-message-edit-sr9.png
    - assets/upload/images/screen-shot-2023-06-28-at-1729-1-3HT.png
    - assets/upload/images/frame-21-Yz5.png
    - assets/upload/images/ellipse-2-qp5.png
    - assets/upload/images/icon-bell-tdF.png
    - assets/upload/images/icon-magnifying-glass-ATb.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-2-mGu.png
    - assets/design/images/ic-round-visibility.png
    - assets/design/images/tabler-wind.png
    - assets/upload/images/ellipse-2-AmP.png
    - assets/upload/images/ellipse-3-Vys.png
    - assets/upload/images/auto-group-v4sf.png
    - assets/upload/images/footer-T5B.png
    - assets/upload/images/icon-trip-map-uZs.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-1-Pvq.png
    - assets/upload/images/tengah.png
    - assets/design/images/carbon-humidity.png
    - assets/design/images/ion-speedometer.png
    - assets/design/images/vector.png
    - assets/design/images/sun-cloud-mid-rain.png
    - assets/design/images/eva-arrow-ios-forward-fill.png
    - assets/design/images/big-rain-drops.png
    - assets/design/images/ic-round-arrow-back-ios-new.png
    - assets/design/images/moon-cloud-fast-wind.png
    - assets/design/images/sun-cloud-mid-rain-bg.png
    - assets/design/images/big-rain-drops-pYy.png
    - assets/design/images/group-11.png
    - assets/design/images/sun-cloud-little-rain.png
    - assets/design/images/sun-cloud-angled-rain.png
    - assets/upload/images/screen-shot-2023-06-28-at-1735-2-bg-VAR.png
    - assets/design/images/moon-cloud-fast-wind-CwK.png
    - assets/design/images/mask-group.png
    - assets/design/images/group-12.png
    - assets/design/images/group-10.png
    - assets/design/images/vector-377.png
    - assets/design/images/vector-nAu.png
    - assets/design/images/cloud-3-zap.png
    - assets/design/images/vector-TQD.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
